namespace Club_Management_System
{
    partial class Login
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Login));
            this.mySiticoneLicenseSettings1 = new SiticoneNetFrameworkUI.MySiticoneLicenseSettings();
            this.siticonePanel2 = new SiticoneNetFrameworkUI.SiticonePanel();
            this.siticoneCheckBox1 = new SiticoneNetFrameworkUI.SiticoneCheckBox();
            this.siticoneTextBox7 = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.siticoneButton1 = new SiticoneNetFrameworkUI.SiticoneButton();
            this.siticoneTextButton2 = new SiticoneNetFrameworkUI.SiticoneTextButton();
            this.siticoneTextButton1 = new SiticoneNetFrameworkUI.SiticoneTextButton();
            this.siticoneTextBox6 = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.siticoneTextBox5 = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.siticoneTextBox4 = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.siticoneTextBox3 = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.siticoneTextBox2 = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.siticoneTextBox1 = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.siticonePanel1 = new SiticoneNetFrameworkUI.SiticonePanel();
            this.siticoneImageButton1 = new SiticoneNetFrameworkUI.SiticoneImageButton();
            this.siticoneTextBox11 = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.siticoneTextBox8 = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.siticoneTextBox10 = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.siticoneTextBox9 = new SiticoneNetFrameworkUI.SiticoneTextBox();
            this.siticonePanel2.SuspendLayout();
            this.siticonePanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // mySiticoneLicenseSettings1
            // 
            this.mySiticoneLicenseSettings1.OpenLicenseSettings = null;
            // 
            // siticonePanel2
            // 
            this.siticonePanel2.AcrylicTintColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticonePanel2.BackColor = System.Drawing.Color.Black;
            this.siticonePanel2.BorderAlignment = System.Drawing.Drawing2D.PenAlignment.Center;
            this.siticonePanel2.BorderDashPattern = null;
            this.siticonePanel2.BorderGradientEndColor = System.Drawing.Color.DimGray;
            this.siticonePanel2.BorderGradientStartColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.siticonePanel2.BorderThickness = 2F;
            this.siticonePanel2.Controls.Add(this.siticoneCheckBox1);
            this.siticonePanel2.Controls.Add(this.siticoneTextBox7);
            this.siticonePanel2.Controls.Add(this.siticoneButton1);
            this.siticonePanel2.Controls.Add(this.siticoneTextButton2);
            this.siticonePanel2.Controls.Add(this.siticoneTextButton1);
            this.siticonePanel2.Controls.Add(this.siticoneTextBox6);
            this.siticonePanel2.Controls.Add(this.siticoneTextBox5);
            this.siticonePanel2.Controls.Add(this.siticoneTextBox4);
            this.siticonePanel2.Controls.Add(this.siticoneTextBox3);
            this.siticonePanel2.Controls.Add(this.siticoneTextBox2);
            this.siticonePanel2.Controls.Add(this.siticoneTextBox1);
            this.siticonePanel2.CornerRadiusBottomLeft = 20F;
            this.siticonePanel2.CornerRadiusBottomRight = 20F;
            this.siticonePanel2.CornerRadiusTopLeft = 20F;
            this.siticonePanel2.CornerRadiusTopRight = 20F;
            this.siticonePanel2.EnableAcrylicEffect = false;
            this.siticonePanel2.EnableMicaEffect = false;
            this.siticonePanel2.EnableRippleEffect = false;
            this.siticonePanel2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticonePanel2.GradientColors = new System.Drawing.Color[] {
        System.Drawing.Color.White,
        System.Drawing.Color.LightGray,
        System.Drawing.Color.Gray};
            this.siticonePanel2.GradientPositions = new float[] {
        0F,
        0.5F,
        1F};
            this.siticonePanel2.Location = new System.Drawing.Point(569, 12);
            this.siticonePanel2.Name = "siticonePanel2";
            this.siticonePanel2.PatternStyle = System.Drawing.Drawing2D.HatchStyle.LargeGrid;
            this.siticonePanel2.RippleAlpha = 50;
            this.siticonePanel2.RippleAlphaDecrement = 3;
            this.siticonePanel2.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticonePanel2.RippleMaxSize = 600F;
            this.siticonePanel2.RippleSpeed = 15F;
            this.siticonePanel2.ShowBorder = true;
            this.siticonePanel2.Size = new System.Drawing.Size(429, 574);
            this.siticonePanel2.TabIndex = 1;
            this.siticonePanel2.TabStop = true;
            this.siticonePanel2.TrackSystemTheme = false;
            this.siticonePanel2.UseBorderGradient = false;
            this.siticonePanel2.UseMultiGradient = false;
            this.siticonePanel2.UsePatternTexture = false;
            this.siticonePanel2.UseRadialGradient = false;
            this.siticonePanel2.Paint += new System.Windows.Forms.PaintEventHandler(this.siticonePanel2_Paint);
            // 
            // siticoneCheckBox1
            // 
            this.siticoneCheckBox1.AccessibleName = "Remember Me";
            this.siticoneCheckBox1.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.siticoneCheckBox1.AllowIndeterminate = false;
            this.siticoneCheckBox1.BackColor = System.Drawing.Color.Transparent;
            this.siticoneCheckBox1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(180)))), ((int)(((byte)(180)))));
            this.siticoneCheckBox1.BorderWidth = 2;
            this.siticoneCheckBox1.BottomLeftRadius = 3;
            this.siticoneCheckBox1.BottomRightRadius = 3;
            this.siticoneCheckBox1.CanBeep = true;
            this.siticoneCheckBox1.CanShake = true;
            this.siticoneCheckBox1.CheckBoxSize = 20;
            this.siticoneCheckBox1.Checked = false;
            this.siticoneCheckBox1.CheckedBackColor = System.Drawing.Color.Silver;
            this.siticoneCheckBox1.CheckedBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.siticoneCheckBox1.CheckmarkColor = System.Drawing.Color.White;
            this.siticoneCheckBox1.CheckState = SiticoneNetFrameworkUI.CheckState.Unchecked;
            this.siticoneCheckBox1.ContainerBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneCheckBox1.ContainerBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneCheckBox1.ContainerBorderWidth = 1;
            this.siticoneCheckBox1.ContainerBottomLeftRadius = 8;
            this.siticoneCheckBox1.ContainerBottomRightRadius = 8;
            this.siticoneCheckBox1.ContainerCheckedBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.siticoneCheckBox1.ContainerCheckedColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(56)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.siticoneCheckBox1.ContainerCheckedHoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(56)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.siticoneCheckBox1.ContainerCheckedPressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(56)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.siticoneCheckBox1.ContainerHoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneCheckBox1.ContainerPadding = 8;
            this.siticoneCheckBox1.ContainerPressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneCheckBox1.ContainerTopLeftRadius = 8;
            this.siticoneCheckBox1.ContainerTopRightRadius = 8;
            this.siticoneCheckBox1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.siticoneCheckBox1.EnableRippleEffect = true;
            this.siticoneCheckBox1.FocusBorderWidth = 2;
            this.siticoneCheckBox1.FocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.siticoneCheckBox1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.siticoneCheckBox1.ForeColor = System.Drawing.Color.Silver;
            this.siticoneCheckBox1.HoverBackColor = System.Drawing.Color.Gainsboro;
            this.siticoneCheckBox1.IndeterminateBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.siticoneCheckBox1.IndeterminateColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(180)))), ((int)(((byte)(180)))));
            this.siticoneCheckBox1.IsContained = false;
            this.siticoneCheckBox1.IsReadOnly = false;
            this.siticoneCheckBox1.Location = new System.Drawing.Point(40, 356);
            this.siticoneCheckBox1.MinimumSize = new System.Drawing.Size(178, 24);
            this.siticoneCheckBox1.Name = "siticoneCheckBox1";
            this.siticoneCheckBox1.PressedBackColor = System.Drawing.Color.DarkGray;
            this.siticoneCheckBox1.ShowFocusCue = false;
            this.siticoneCheckBox1.Size = new System.Drawing.Size(178, 24);
            this.siticoneCheckBox1.Style = SiticoneNetFrameworkUI.CheckBoxStyle.Minimal;
            this.siticoneCheckBox1.SwitchCheckedTrackColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(56)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.siticoneCheckBox1.SwitchTrackColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.siticoneCheckBox1.TabIndex = 10;
            this.siticoneCheckBox1.Text = "Remember Me";
            this.siticoneCheckBox1.TopLeftRadius = 3;
            this.siticoneCheckBox1.TopRightRadius = 3;
            this.siticoneCheckBox1.UncheckedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(250)))), ((int)(((byte)(250)))));
            this.siticoneCheckBox1.Click += new System.EventHandler(this.siticoneCheckBox1_Click);
            // 
            // siticoneTextBox7
            // 
            this.siticoneTextBox7.AccessibleDescription = "A customizable text input field.";
            this.siticoneTextBox7.AccessibleName = "Text Box";
            this.siticoneTextBox7.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.siticoneTextBox7.BackColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox7.BlinkCount = 3;
            this.siticoneTextBox7.BlinkShadow = false;
            this.siticoneTextBox7.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox7.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox7.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox7.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox7.CanShake = true;
            this.siticoneTextBox7.ContinuousBlink = false;
            this.siticoneTextBox7.Cursor = System.Windows.Forms.Cursors.Default;
            this.siticoneTextBox7.CursorBlinkRate = 500;
            this.siticoneTextBox7.CursorColor = System.Drawing.Color.Black;
            this.siticoneTextBox7.CursorHeight = 26;
            this.siticoneTextBox7.CursorOffset = 0;
            this.siticoneTextBox7.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.siticoneTextBox7.CursorWidth = 1;
            this.siticoneTextBox7.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox7.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox7.DisabledTextColor = System.Drawing.Color.Gray;
            this.siticoneTextBox7.EnableDropShadow = false;
            this.siticoneTextBox7.FillColor1 = System.Drawing.Color.White;
            this.siticoneTextBox7.FillColor2 = System.Drawing.Color.White;
            this.siticoneTextBox7.Font = new System.Drawing.Font("Comic Sans MS", 10.2F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneTextBox7.ForeColor = System.Drawing.Color.Silver;
            this.siticoneTextBox7.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.siticoneTextBox7.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.siticoneTextBox7.IsEnabled = true;
            this.siticoneTextBox7.IsReadOnly = true;
            this.siticoneTextBox7.Location = new System.Drawing.Point(21, 120);
            this.siticoneTextBox7.Name = "siticoneTextBox7";
            this.siticoneTextBox7.PlaceholderColor = System.Drawing.Color.Gray;
            this.siticoneTextBox7.PlaceholderText = "Enter text here...";
            this.siticoneTextBox7.ReadOnlyBorderColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox7.ReadOnlyBorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox7.ReadOnlyFillColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox7.ReadOnlyFillColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox7.ReadOnlyPlaceholderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox7.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox7.ShadowAnimationDuration = 1;
            this.siticoneTextBox7.ShadowBlur = 10;
            this.siticoneTextBox7.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneTextBox7.ShowBorder = false;
            this.siticoneTextBox7.Size = new System.Drawing.Size(393, 20);
            this.siticoneTextBox7.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox7.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox7.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.siticoneTextBox7.SolidFillColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox7.TabIndex = 9;
            this.siticoneTextBox7.Text = "dashboard";
            this.siticoneTextBox7.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.siticoneTextBox7.ValidationErrorMessage = "Invalid input.";
            this.siticoneTextBox7.ValidationFunction = null;
            this.siticoneTextBox7.Click += new System.EventHandler(this.siticoneTextBox7_Click);
            // 
            // siticoneButton1
            // 
            this.siticoneButton1.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.siticoneButton1.AccessibleName = "Sign In";
            this.siticoneButton1.AutoSizeBasedOnText = false;
            this.siticoneButton1.BackColor = System.Drawing.Color.Transparent;
            this.siticoneButton1.BadgeBackColor = System.Drawing.Color.Black;
            this.siticoneButton1.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.siticoneButton1.BadgeValue = 0;
            this.siticoneButton1.BadgeValueForeColor = System.Drawing.Color.White;
            this.siticoneButton1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(168)))), ((int)(((byte)(0)))));
            this.siticoneButton1.BorderWidth = 2;
            this.siticoneButton1.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(207)))), ((int)(((byte)(61)))));
            this.siticoneButton1.ButtonImage = null;
            this.siticoneButton1.ButtonTextLeftPadding = 0;
            this.siticoneButton1.CanBeep = true;
            this.siticoneButton1.CanGlow = false;
            this.siticoneButton1.CanShake = true;
            this.siticoneButton1.ContextMenuStripEx = null;
            this.siticoneButton1.CornerRadiusBottomLeft = 16;
            this.siticoneButton1.CornerRadiusBottomRight = 16;
            this.siticoneButton1.CornerRadiusTopLeft = 16;
            this.siticoneButton1.CornerRadiusTopRight = 16;
            this.siticoneButton1.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.siticoneButton1.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.siticoneButton1.EnableLongPress = false;
            this.siticoneButton1.EnablePressAnimation = true;
            this.siticoneButton1.EnableRippleEffect = true;
            this.siticoneButton1.EnableShadow = false;
            this.siticoneButton1.EnableTextWrapping = false;
            this.siticoneButton1.Font = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneButton1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.siticoneButton1.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticoneButton1.GlowIntensity = 100;
            this.siticoneButton1.GlowRadius = 20F;
            this.siticoneButton1.GradientBackground = false;
            this.siticoneButton1.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(200)))), ((int)(((byte)(63)))));
            this.siticoneButton1.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.siticoneButton1.HintText = null;
            this.siticoneButton1.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(168)))), ((int)(((byte)(0)))));
            this.siticoneButton1.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton1.HoverTextColor = System.Drawing.Color.Black;
            this.siticoneButton1.HoverTransitionDuration = 250;
            this.siticoneButton1.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.siticoneButton1.ImagePadding = 5;
            this.siticoneButton1.ImageSize = new System.Drawing.Size(16, 16);
            this.siticoneButton1.IsRadial = true;
            this.siticoneButton1.IsReadOnly = false;
            this.siticoneButton1.IsToggleButton = false;
            this.siticoneButton1.IsToggled = false;
            this.siticoneButton1.Location = new System.Drawing.Point(30, 395);
            this.siticoneButton1.LongPressDurationMS = 1000;
            this.siticoneButton1.Name = "siticoneButton1";
            this.siticoneButton1.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton1.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.siticoneButton1.ParticleCount = 15;
            this.siticoneButton1.PressAnimationScale = 0.97F;
            this.siticoneButton1.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(168)))), ((int)(((byte)(0)))));
            this.siticoneButton1.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton1.PressTransitionDuration = 150;
            this.siticoneButton1.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneButton1.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticoneButton1.RippleOpacity = 0.3F;
            this.siticoneButton1.RippleRadiusMultiplier = 0.6F;
            this.siticoneButton1.ShadowBlur = 5;
            this.siticoneButton1.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneButton1.ShadowOffset = new System.Drawing.Point(2, 2);
            this.siticoneButton1.ShakeDuration = 500;
            this.siticoneButton1.ShakeIntensity = 5;
            this.siticoneButton1.Size = new System.Drawing.Size(327, 36);
            this.siticoneButton1.TabIndex = 8;
            this.siticoneButton1.Text = "Sign In";
            this.siticoneButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.siticoneButton1.TextColor = System.Drawing.Color.Black;
            this.siticoneButton1.TooltipText = null;
            this.siticoneButton1.UseAdvancedRendering = true;
            this.siticoneButton1.UseParticles = false;
            this.siticoneButton1.Click += new System.EventHandler(this.siticoneButton1_Click);
            // 
            // siticoneTextButton2
            // 
            this.siticoneTextButton2.AccessibleDescription = "A text-centric button control that accepts input through mouse, touch, and keyboa" +
    "rd";
            this.siticoneTextButton2.AccessibleName = "";
            this.siticoneTextButton2.AutoSizeBasedOnText = true;
            this.siticoneTextButton2.BackColor = System.Drawing.Color.Transparent;
            this.siticoneTextButton2.CanBeep = true;
            this.siticoneTextButton2.CanGlow = false;
            this.siticoneTextButton2.CanShake = true;
            this.siticoneTextButton2.ContextMenuStripEx = null;
            this.siticoneTextButton2.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.siticoneTextButton2.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.siticoneTextButton2.EnableLongPress = false;
            this.siticoneTextButton2.EnablePressAnimation = false;
            this.siticoneTextButton2.EnableRippleEffect = true;
            this.siticoneTextButton2.EnableShadow = false;
            this.siticoneTextButton2.EnableTextWrapping = false;
            this.siticoneTextButton2.Font = new System.Drawing.Font("Segoe UI", 10.2F);
            this.siticoneTextButton2.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticoneTextButton2.GlowIntensity = 100;
            this.siticoneTextButton2.GlowRadius = 20F;
            this.siticoneTextButton2.HintText = null;
            this.siticoneTextButton2.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneTextButton2.HoverShowUnderline = true;
            this.siticoneTextButton2.HoverTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(105)))), ((int)(((byte)(192)))));
            this.siticoneTextButton2.HoverTransitionDuration = 250;
            this.siticoneTextButton2.IsReadOnly = false;
            this.siticoneTextButton2.IsToggleButton = false;
            this.siticoneTextButton2.IsToggled = false;
            this.siticoneTextButton2.Location = new System.Drawing.Point(92, 15);
            this.siticoneTextButton2.LongPressDurationMS = 1000;
            this.siticoneTextButton2.Name = "siticoneTextButton2";
            this.siticoneTextButton2.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneTextButton2.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.siticoneTextButton2.ParticleCount = 15;
            this.siticoneTextButton2.PressAnimationScale = 0.97F;
            this.siticoneTextButton2.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneTextButton2.PressTransitionDuration = 150;
            this.siticoneTextButton2.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneTextButton2.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(105)))), ((int)(((byte)(192)))));
            this.siticoneTextButton2.RippleOpacity = 0.3F;
            this.siticoneTextButton2.RippleRadiusMultiplier = 0.6F;
            this.siticoneTextButton2.ShadowBlur = 5;
            this.siticoneTextButton2.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneTextButton2.ShadowOffset = new System.Drawing.Point(2, 2);
            this.siticoneTextButton2.ShakeDuration = 500;
            this.siticoneTextButton2.ShakeIntensity = 5;
            this.siticoneTextButton2.ShowUnderline = false;
            this.siticoneTextButton2.Size = new System.Drawing.Size(10, 6);
            this.siticoneTextButton2.TabIndex = 7;
            this.siticoneTextButton2.Text = "Text Button";
            this.siticoneTextButton2.TextBottomPadding = 0;
            this.siticoneTextButton2.TextColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.siticoneTextButton2.TextLeftPadding = 0;
            this.siticoneTextButton2.TextRightPadding = 0;
            this.siticoneTextButton2.TextTopPadding = 0;
            this.siticoneTextButton2.TextTransform = SiticoneNetFrameworkUI.SiticoneTextButton.TextButtonTextTransform.None;
            this.siticoneTextButton2.TooltipText = null;
            this.siticoneTextButton2.UnderlineColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(105)))), ((int)(((byte)(192)))));
            this.siticoneTextButton2.UnderlineHeight = 1;
            this.siticoneTextButton2.UnderlineStyle = SiticoneNetFrameworkUI.SiticoneTextButton.TextButtonUnderlineStyle.Solid;
            this.siticoneTextButton2.UseAdvancedRendering = true;
            this.siticoneTextButton2.UseParticles = false;
            this.siticoneTextButton2.Click += new System.EventHandler(this.siticoneTextButton2_Click);
            // 
            // siticoneTextButton1
            // 
            this.siticoneTextButton1.AccessibleDescription = "A text-centric button control that accepts input through mouse, touch, and keyboa" +
    "rd";
            this.siticoneTextButton1.AccessibleName = "     Forgot Password?       ";
            this.siticoneTextButton1.AutoSizeBasedOnText = true;
            this.siticoneTextButton1.BackColor = System.Drawing.Color.Transparent;
            this.siticoneTextButton1.CanBeep = true;
            this.siticoneTextButton1.CanGlow = false;
            this.siticoneTextButton1.CanShake = true;
            this.siticoneTextButton1.ContextMenuStripEx = null;
            this.siticoneTextButton1.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.siticoneTextButton1.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.siticoneTextButton1.EnableLongPress = false;
            this.siticoneTextButton1.EnablePressAnimation = false;
            this.siticoneTextButton1.EnableRippleEffect = true;
            this.siticoneTextButton1.EnableShadow = false;
            this.siticoneTextButton1.EnableTextWrapping = false;
            this.siticoneTextButton1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneTextButton1.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticoneTextButton1.GlowIntensity = 100;
            this.siticoneTextButton1.GlowRadius = 20F;
            this.siticoneTextButton1.HintText = null;
            this.siticoneTextButton1.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneTextButton1.HoverShowUnderline = true;
            this.siticoneTextButton1.HoverTextColor = System.Drawing.Color.Black;
            this.siticoneTextButton1.HoverTransitionDuration = 250;
            this.siticoneTextButton1.IsReadOnly = false;
            this.siticoneTextButton1.IsToggleButton = false;
            this.siticoneTextButton1.IsToggled = false;
            this.siticoneTextButton1.Location = new System.Drawing.Point(174, 268);
            this.siticoneTextButton1.LongPressDurationMS = 1000;
            this.siticoneTextButton1.Name = "siticoneTextButton1";
            this.siticoneTextButton1.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneTextButton1.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.siticoneTextButton1.ParticleCount = 15;
            this.siticoneTextButton1.PressAnimationScale = 0.97F;
            this.siticoneTextButton1.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneTextButton1.PressTransitionDuration = 150;
            this.siticoneTextButton1.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneTextButton1.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(105)))), ((int)(((byte)(192)))));
            this.siticoneTextButton1.RippleOpacity = 0.3F;
            this.siticoneTextButton1.RippleRadiusMultiplier = 0.6F;
            this.siticoneTextButton1.ShadowBlur = 5;
            this.siticoneTextButton1.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneTextButton1.ShadowOffset = new System.Drawing.Point(2, 2);
            this.siticoneTextButton1.ShakeDuration = 500;
            this.siticoneTextButton1.ShakeIntensity = 5;
            this.siticoneTextButton1.ShowUnderline = false;
            this.siticoneTextButton1.Size = new System.Drawing.Size(187, 28);
            this.siticoneTextButton1.TabIndex = 6;
            this.siticoneTextButton1.Text = "     Forgot Password?       ";
            this.siticoneTextButton1.TextBottomPadding = 0;
            this.siticoneTextButton1.TextColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(207)))), ((int)(((byte)(61)))));
            this.siticoneTextButton1.TextLeftPadding = 0;
            this.siticoneTextButton1.TextRightPadding = 0;
            this.siticoneTextButton1.TextTopPadding = 0;
            this.siticoneTextButton1.TextTransform = SiticoneNetFrameworkUI.SiticoneTextButton.TextButtonTextTransform.None;
            this.siticoneTextButton1.TooltipText = null;
            this.siticoneTextButton1.UnderlineColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(105)))), ((int)(((byte)(192)))));
            this.siticoneTextButton1.UnderlineHeight = 1;
            this.siticoneTextButton1.UnderlineStyle = SiticoneNetFrameworkUI.SiticoneTextButton.TextButtonUnderlineStyle.Solid;
            this.siticoneTextButton1.UseAdvancedRendering = true;
            this.siticoneTextButton1.UseParticles = false;
            this.siticoneTextButton1.Click += new System.EventHandler(this.siticoneTextButton1_Click);
            // 
            // siticoneTextBox6
            // 
            this.siticoneTextBox6.AccessibleDescription = "A customizable text input field.";
            this.siticoneTextBox6.AccessibleName = "Text Box";
            this.siticoneTextBox6.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.siticoneTextBox6.BackColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox6.BlinkCount = 3;
            this.siticoneTextBox6.BlinkShadow = false;
            this.siticoneTextBox6.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox6.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox6.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox6.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox6.CanShake = true;
            this.siticoneTextBox6.ContinuousBlink = false;
            this.siticoneTextBox6.Cursor = System.Windows.Forms.Cursors.Default;
            this.siticoneTextBox6.CursorBlinkRate = 500;
            this.siticoneTextBox6.CursorColor = System.Drawing.Color.Black;
            this.siticoneTextBox6.CursorHeight = 26;
            this.siticoneTextBox6.CursorOffset = 0;
            this.siticoneTextBox6.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.siticoneTextBox6.CursorWidth = 1;
            this.siticoneTextBox6.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox6.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox6.DisabledTextColor = System.Drawing.Color.Gray;
            this.siticoneTextBox6.EnableDropShadow = false;
            this.siticoneTextBox6.FillColor1 = System.Drawing.Color.White;
            this.siticoneTextBox6.FillColor2 = System.Drawing.Color.White;
            this.siticoneTextBox6.Font = new System.Drawing.Font("Britannic Bold", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneTextBox6.ForeColor = System.Drawing.Color.Gainsboro;
            this.siticoneTextBox6.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.siticoneTextBox6.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.siticoneTextBox6.IsEnabled = true;
            this.siticoneTextBox6.IsReadOnly = true;
            this.siticoneTextBox6.Location = new System.Drawing.Point(21, 268);
            this.siticoneTextBox6.Name = "siticoneTextBox6";
            this.siticoneTextBox6.PlaceholderColor = System.Drawing.Color.Gray;
            this.siticoneTextBox6.PlaceholderText = "Enter text here...";
            this.siticoneTextBox6.ReadOnlyBorderColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox6.ReadOnlyBorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox6.ReadOnlyFillColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox6.ReadOnlyFillColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox6.ReadOnlyPlaceholderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox6.ShadowAnimationDuration = 1;
            this.siticoneTextBox6.ShadowBlur = 10;
            this.siticoneTextBox6.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneTextBox6.ShowBorder = false;
            this.siticoneTextBox6.Size = new System.Drawing.Size(111, 30);
            this.siticoneTextBox6.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox6.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox6.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.siticoneTextBox6.SolidFillColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox6.TabIndex = 5;
            this.siticoneTextBox6.Text = "Password";
            this.siticoneTextBox6.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.siticoneTextBox6.ValidationErrorMessage = "Invalid input.";
            this.siticoneTextBox6.ValidationFunction = null;
            this.siticoneTextBox6.Click += new System.EventHandler(this.siticoneTextBox6_Click);
            // 
            // siticoneTextBox5
            // 
            this.siticoneTextBox5.AccessibleDescription = "A customizable text input field.";
            this.siticoneTextBox5.AccessibleName = "Text Box";
            this.siticoneTextBox5.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.siticoneTextBox5.BackColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox5.BlinkCount = 3;
            this.siticoneTextBox5.BlinkShadow = false;
            this.siticoneTextBox5.BorderColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(205)))), ((int)(((byte)(164)))), ((int)(((byte)(44)))));
            this.siticoneTextBox5.BorderColor2 = System.Drawing.Color.SteelBlue;
            this.siticoneTextBox5.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox5.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox5.BorderSize = 2;
            this.siticoneTextBox5.CanShake = true;
            this.siticoneTextBox5.ContinuousBlink = false;
            this.siticoneTextBox5.CornerRadiusBottomLeft = 10;
            this.siticoneTextBox5.CornerRadiusBottomRight = 10;
            this.siticoneTextBox5.CornerRadiusTopLeft = 10;
            this.siticoneTextBox5.CornerRadiusTopRight = 10;
            this.siticoneTextBox5.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.siticoneTextBox5.CursorBlinkRate = 500;
            this.siticoneTextBox5.CursorColor = System.Drawing.Color.Black;
            this.siticoneTextBox5.CursorHeight = 26;
            this.siticoneTextBox5.CursorOffset = 0;
            this.siticoneTextBox5.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.siticoneTextBox5.CursorWidth = 1;
            this.siticoneTextBox5.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox5.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox5.DisabledTextColor = System.Drawing.Color.Gray;
            this.siticoneTextBox5.EnableDropShadow = false;
            this.siticoneTextBox5.FillColor1 = System.Drawing.Color.White;
            this.siticoneTextBox5.FillColor2 = System.Drawing.Color.White;
            this.siticoneTextBox5.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.siticoneTextBox5.ForeColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox5.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.siticoneTextBox5.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.siticoneTextBox5.IsEnabled = true;
            this.siticoneTextBox5.Location = new System.Drawing.Point(30, 304);
            this.siticoneTextBox5.Name = "siticoneTextBox5";
            this.siticoneTextBox5.PlaceholderColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox5.PlaceholderText = "Enter Your ID Here";
            this.siticoneTextBox5.ReadOnlyBorderColor1 = System.Drawing.Color.LightGray;
            this.siticoneTextBox5.ReadOnlyBorderColor2 = System.Drawing.Color.LightGray;
            this.siticoneTextBox5.ReadOnlyFillColor1 = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox5.ReadOnlyFillColor2 = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox5.ReadOnlyPlaceholderColor = System.Drawing.Color.DarkGray;
            this.siticoneTextBox5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox5.ShadowAnimationDuration = 1;
            this.siticoneTextBox5.ShadowBlur = 10;
            this.siticoneTextBox5.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneTextBox5.Size = new System.Drawing.Size(327, 36);
            this.siticoneTextBox5.SolidBorderColor = System.Drawing.Color.DarkGray;
            this.siticoneTextBox5.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(209)))), ((int)(((byte)(170)))), ((int)(((byte)(50)))));
            this.siticoneTextBox5.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.siticoneTextBox5.SolidFillColor = System.Drawing.Color.DimGray;
            this.siticoneTextBox5.TabIndex = 4;
            this.siticoneTextBox5.TextPadding = new System.Windows.Forms.Padding(11, 2, 11, 2);
            this.siticoneTextBox5.ValidationErrorMessage = "Invalid input.";
            this.siticoneTextBox5.ValidationFunction = null;
            this.siticoneTextBox5.Click += new System.EventHandler(this.siticoneTextBox5_Click);
            // 
            // siticoneTextBox4
            // 
            this.siticoneTextBox4.AccessibleDescription = "A customizable text input field.";
            this.siticoneTextBox4.AccessibleName = "Text Box";
            this.siticoneTextBox4.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.siticoneTextBox4.BackColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox4.BlinkCount = 3;
            this.siticoneTextBox4.BlinkShadow = false;
            this.siticoneTextBox4.BorderColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(205)))), ((int)(((byte)(164)))), ((int)(((byte)(44)))));
            this.siticoneTextBox4.BorderColor2 = System.Drawing.Color.SteelBlue;
            this.siticoneTextBox4.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox4.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox4.BorderSize = 2;
            this.siticoneTextBox4.CanShake = true;
            this.siticoneTextBox4.ContinuousBlink = false;
            this.siticoneTextBox4.CornerRadiusBottomLeft = 10;
            this.siticoneTextBox4.CornerRadiusBottomRight = 10;
            this.siticoneTextBox4.CornerRadiusTopLeft = 10;
            this.siticoneTextBox4.CornerRadiusTopRight = 10;
            this.siticoneTextBox4.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.siticoneTextBox4.CursorBlinkRate = 500;
            this.siticoneTextBox4.CursorColor = System.Drawing.Color.Black;
            this.siticoneTextBox4.CursorHeight = 26;
            this.siticoneTextBox4.CursorOffset = 0;
            this.siticoneTextBox4.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.siticoneTextBox4.CursorWidth = 1;
            this.siticoneTextBox4.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox4.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox4.DisabledTextColor = System.Drawing.Color.Gray;
            this.siticoneTextBox4.EnableDropShadow = false;
            this.siticoneTextBox4.FillColor1 = System.Drawing.Color.White;
            this.siticoneTextBox4.FillColor2 = System.Drawing.Color.White;
            this.siticoneTextBox4.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.siticoneTextBox4.ForeColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox4.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.siticoneTextBox4.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.siticoneTextBox4.IsEnabled = true;
            this.siticoneTextBox4.Location = new System.Drawing.Point(30, 210);
            this.siticoneTextBox4.Name = "siticoneTextBox4";
            this.siticoneTextBox4.PlaceholderColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox4.PlaceholderText = "Enter Your ID Here";
            this.siticoneTextBox4.ReadOnlyBorderColor1 = System.Drawing.Color.LightGray;
            this.siticoneTextBox4.ReadOnlyBorderColor2 = System.Drawing.Color.LightGray;
            this.siticoneTextBox4.ReadOnlyFillColor1 = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox4.ReadOnlyFillColor2 = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox4.ReadOnlyPlaceholderColor = System.Drawing.Color.DarkGray;
            this.siticoneTextBox4.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox4.ShadowAnimationDuration = 1;
            this.siticoneTextBox4.ShadowBlur = 10;
            this.siticoneTextBox4.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneTextBox4.Size = new System.Drawing.Size(327, 36);
            this.siticoneTextBox4.SolidBorderColor = System.Drawing.Color.DarkGray;
            this.siticoneTextBox4.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(209)))), ((int)(((byte)(170)))), ((int)(((byte)(50)))));
            this.siticoneTextBox4.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.siticoneTextBox4.SolidFillColor = System.Drawing.Color.DimGray;
            this.siticoneTextBox4.TabIndex = 3;
            this.siticoneTextBox4.TextPadding = new System.Windows.Forms.Padding(11, 2, 11, 2);
            this.siticoneTextBox4.ValidationErrorMessage = "Invalid input.";
            this.siticoneTextBox4.ValidationFunction = null;
            this.siticoneTextBox4.Click += new System.EventHandler(this.siticoneTextBox4_Click);
            // 
            // siticoneTextBox3
            // 
            this.siticoneTextBox3.AccessibleDescription = "A customizable text input field.";
            this.siticoneTextBox3.AccessibleName = "Text Box";
            this.siticoneTextBox3.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.siticoneTextBox3.BackColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox3.BlinkCount = 3;
            this.siticoneTextBox3.BlinkShadow = false;
            this.siticoneTextBox3.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox3.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox3.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox3.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox3.CanShake = true;
            this.siticoneTextBox3.ContinuousBlink = false;
            this.siticoneTextBox3.Cursor = System.Windows.Forms.Cursors.Default;
            this.siticoneTextBox3.CursorBlinkRate = 500;
            this.siticoneTextBox3.CursorColor = System.Drawing.Color.Black;
            this.siticoneTextBox3.CursorHeight = 26;
            this.siticoneTextBox3.CursorOffset = 0;
            this.siticoneTextBox3.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.siticoneTextBox3.CursorWidth = 1;
            this.siticoneTextBox3.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox3.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox3.DisabledTextColor = System.Drawing.Color.Gray;
            this.siticoneTextBox3.EnableDropShadow = false;
            this.siticoneTextBox3.FillColor1 = System.Drawing.Color.White;
            this.siticoneTextBox3.FillColor2 = System.Drawing.Color.White;
            this.siticoneTextBox3.Font = new System.Drawing.Font("Britannic Bold", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneTextBox3.ForeColor = System.Drawing.Color.Gainsboro;
            this.siticoneTextBox3.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.siticoneTextBox3.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.siticoneTextBox3.IsEnabled = true;
            this.siticoneTextBox3.IsReadOnly = true;
            this.siticoneTextBox3.Location = new System.Drawing.Point(30, 174);
            this.siticoneTextBox3.Name = "siticoneTextBox3";
            this.siticoneTextBox3.PlaceholderColor = System.Drawing.Color.Gray;
            this.siticoneTextBox3.PlaceholderText = "Enter text here...";
            this.siticoneTextBox3.ReadOnlyBorderColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox3.ReadOnlyBorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox3.ReadOnlyFillColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox3.ReadOnlyFillColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox3.ReadOnlyPlaceholderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox3.ShadowAnimationDuration = 1;
            this.siticoneTextBox3.ShadowBlur = 10;
            this.siticoneTextBox3.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneTextBox3.ShowBorder = false;
            this.siticoneTextBox3.Size = new System.Drawing.Size(154, 30);
            this.siticoneTextBox3.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox3.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox3.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.siticoneTextBox3.SolidFillColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox3.TabIndex = 2;
            this.siticoneTextBox3.Text = "Identity Number  ";
            this.siticoneTextBox3.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.siticoneTextBox3.ValidationErrorMessage = "Invalid input.";
            this.siticoneTextBox3.ValidationFunction = null;
            this.siticoneTextBox3.Click += new System.EventHandler(this.siticoneTextBox3_Click);
            // 
            // siticoneTextBox2
            // 
            this.siticoneTextBox2.AccessibleDescription = "A customizable text input field.";
            this.siticoneTextBox2.AccessibleName = "Text Box";
            this.siticoneTextBox2.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.siticoneTextBox2.BackColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox2.BlinkCount = 3;
            this.siticoneTextBox2.BlinkShadow = false;
            this.siticoneTextBox2.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox2.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox2.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox2.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox2.CanShake = true;
            this.siticoneTextBox2.ContinuousBlink = false;
            this.siticoneTextBox2.Cursor = System.Windows.Forms.Cursors.Default;
            this.siticoneTextBox2.CursorBlinkRate = 500;
            this.siticoneTextBox2.CursorColor = System.Drawing.Color.Black;
            this.siticoneTextBox2.CursorHeight = 26;
            this.siticoneTextBox2.CursorOffset = 0;
            this.siticoneTextBox2.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.siticoneTextBox2.CursorWidth = 1;
            this.siticoneTextBox2.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox2.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox2.DisabledTextColor = System.Drawing.Color.Gray;
            this.siticoneTextBox2.EnableDropShadow = false;
            this.siticoneTextBox2.FillColor1 = System.Drawing.Color.White;
            this.siticoneTextBox2.FillColor2 = System.Drawing.Color.White;
            this.siticoneTextBox2.Font = new System.Drawing.Font("Comic Sans MS", 10.2F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneTextBox2.ForeColor = System.Drawing.Color.Silver;
            this.siticoneTextBox2.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.siticoneTextBox2.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.siticoneTextBox2.IsEnabled = true;
            this.siticoneTextBox2.IsReadOnly = true;
            this.siticoneTextBox2.Location = new System.Drawing.Point(21, 93);
            this.siticoneTextBox2.Name = "siticoneTextBox2";
            this.siticoneTextBox2.PlaceholderColor = System.Drawing.Color.Gray;
            this.siticoneTextBox2.PlaceholderText = "Enter text here...";
            this.siticoneTextBox2.ReadOnlyBorderColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox2.ReadOnlyBorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox2.ReadOnlyFillColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox2.ReadOnlyFillColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox2.ReadOnlyPlaceholderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox2.ShadowAnimationDuration = 1;
            this.siticoneTextBox2.ShadowBlur = 10;
            this.siticoneTextBox2.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneTextBox2.ShowBorder = false;
            this.siticoneTextBox2.Size = new System.Drawing.Size(393, 30);
            this.siticoneTextBox2.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox2.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox2.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.siticoneTextBox2.SolidFillColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox2.TabIndex = 1;
            this.siticoneTextBox2.Text = "Please sign in to access your club   ";
            this.siticoneTextBox2.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.siticoneTextBox2.ValidationErrorMessage = "Invalid input.";
            this.siticoneTextBox2.ValidationFunction = null;
            this.siticoneTextBox2.Click += new System.EventHandler(this.siticoneTextBox2_Click);
            // 
            // siticoneTextBox1
            // 
            this.siticoneTextBox1.AccessibleDescription = "A customizable text input field.";
            this.siticoneTextBox1.AccessibleName = "Text Box";
            this.siticoneTextBox1.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.siticoneTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox1.BlinkCount = 3;
            this.siticoneTextBox1.BlinkShadow = false;
            this.siticoneTextBox1.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox1.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox1.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox1.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox1.CanShake = true;
            this.siticoneTextBox1.ContinuousBlink = false;
            this.siticoneTextBox1.Cursor = System.Windows.Forms.Cursors.Default;
            this.siticoneTextBox1.CursorBlinkRate = 500;
            this.siticoneTextBox1.CursorColor = System.Drawing.Color.Black;
            this.siticoneTextBox1.CursorHeight = 26;
            this.siticoneTextBox1.CursorOffset = 0;
            this.siticoneTextBox1.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.siticoneTextBox1.CursorWidth = 1;
            this.siticoneTextBox1.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox1.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox1.DisabledTextColor = System.Drawing.Color.Gray;
            this.siticoneTextBox1.EnableDropShadow = false;
            this.siticoneTextBox1.FillColor1 = System.Drawing.Color.White;
            this.siticoneTextBox1.FillColor2 = System.Drawing.Color.White;
            this.siticoneTextBox1.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneTextBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(207)))), ((int)(((byte)(61)))));
            this.siticoneTextBox1.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.siticoneTextBox1.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.siticoneTextBox1.IsEnabled = true;
            this.siticoneTextBox1.IsReadOnly = true;
            this.siticoneTextBox1.Location = new System.Drawing.Point(21, 28);
            this.siticoneTextBox1.Name = "siticoneTextBox1";
            this.siticoneTextBox1.PlaceholderColor = System.Drawing.Color.Gray;
            this.siticoneTextBox1.PlaceholderText = "Enter text here...";
            this.siticoneTextBox1.ReadOnlyBorderColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox1.ReadOnlyBorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox1.ReadOnlyFillColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox1.ReadOnlyFillColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox1.ReadOnlyPlaceholderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.siticoneTextBox1.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox1.ShadowAnimationDuration = 1;
            this.siticoneTextBox1.ShadowBlur = 10;
            this.siticoneTextBox1.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneTextBox1.ShowBorder = false;
            this.siticoneTextBox1.Size = new System.Drawing.Size(144, 59);
            this.siticoneTextBox1.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox1.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox1.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.siticoneTextBox1.SolidFillColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox1.TabIndex = 0;
            this.siticoneTextBox1.Text = "Sign In";
            this.siticoneTextBox1.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.siticoneTextBox1.ValidationErrorMessage = "Invalid input.";
            this.siticoneTextBox1.ValidationFunction = null;
            this.siticoneTextBox1.Click += new System.EventHandler(this.siticoneTextBox1_Click);
            // 
            // siticonePanel1
            // 
            this.siticonePanel1.AcrylicTintColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticonePanel1.BackColor = System.Drawing.Color.Black;
            this.siticonePanel1.BorderAlignment = System.Drawing.Drawing2D.PenAlignment.Center;
            this.siticonePanel1.BorderDashPattern = null;
            this.siticonePanel1.BorderGradientEndColor = System.Drawing.Color.DimGray;
            this.siticonePanel1.BorderGradientStartColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.siticonePanel1.BorderThickness = 2F;
            this.siticonePanel1.Controls.Add(this.siticoneImageButton1);
            this.siticonePanel1.Controls.Add(this.siticoneTextBox11);
            this.siticonePanel1.Controls.Add(this.siticoneTextBox8);
            this.siticonePanel1.Controls.Add(this.siticoneTextBox10);
            this.siticonePanel1.Controls.Add(this.siticoneTextBox9);
            this.siticonePanel1.CornerRadiusBottomLeft = 20F;
            this.siticonePanel1.CornerRadiusBottomRight = 20F;
            this.siticonePanel1.CornerRadiusTopLeft = 20F;
            this.siticonePanel1.CornerRadiusTopRight = 20F;
            this.siticonePanel1.EnableAcrylicEffect = false;
            this.siticonePanel1.EnableMicaEffect = false;
            this.siticonePanel1.EnableRippleEffect = false;
            this.siticonePanel1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticonePanel1.GradientColors = new System.Drawing.Color[] {
        System.Drawing.Color.White,
        System.Drawing.Color.LightGray,
        System.Drawing.Color.Gray};
            this.siticonePanel1.GradientPositions = new float[] {
        0F,
        0.5F,
        1F};
            this.siticonePanel1.Location = new System.Drawing.Point(130, 12);
            this.siticonePanel1.Name = "siticonePanel1";
            this.siticonePanel1.PatternStyle = System.Drawing.Drawing2D.HatchStyle.LargeGrid;
            this.siticonePanel1.RippleAlpha = 50;
            this.siticonePanel1.RippleAlphaDecrement = 3;
            this.siticonePanel1.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticonePanel1.RippleMaxSize = 600F;
            this.siticonePanel1.RippleSpeed = 15F;
            this.siticonePanel1.ShowBorder = true;
            this.siticonePanel1.Size = new System.Drawing.Size(438, 574);
            this.siticonePanel1.TabIndex = 2;
            this.siticonePanel1.TabStop = true;
            this.siticonePanel1.TrackSystemTheme = false;
            this.siticonePanel1.UseBorderGradient = false;
            this.siticonePanel1.UseMultiGradient = false;
            this.siticonePanel1.UsePatternTexture = false;
            this.siticonePanel1.UseRadialGradient = false;
            this.siticonePanel1.Paint += new System.Windows.Forms.PaintEventHandler(this.siticonePanel1_Paint);
            // 
            // siticoneImageButton1
            // 
            this.siticoneImageButton1.AnimationSpeed = 0.15F;
            this.siticoneImageButton1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.siticoneImageButton1.BackgroundFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.siticoneImageButton1.BadgeAnimationEnabled = true;
            this.siticoneImageButton1.BadgeAnimationSpeed = 0.15F;
            this.siticoneImageButton1.BadgeColor = System.Drawing.Color.DimGray;
            this.siticoneImageButton1.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.siticoneImageButton1.BadgePosition = SiticoneNetFrameworkUI.BadgePositionExt.TopRight;
            this.siticoneImageButton1.BadgeTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.siticoneImageButton1.BadgeValue = 0;
            this.siticoneImageButton1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(80)))), ((int)(((byte)(80)))));
            this.siticoneImageButton1.BorderThickness = 2;
            this.siticoneImageButton1.CanBeep = true;
            this.siticoneImageButton1.CanShake = true;
            this.siticoneImageButton1.CornerRadiusBottomLeft = 0F;
            this.siticoneImageButton1.CornerRadiusBottomRight = 0F;
            this.siticoneImageButton1.CornerRadiusTopLeft = 0F;
            this.siticoneImageButton1.CornerRadiusTopRight = 0F;
            this.siticoneImageButton1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.siticoneImageButton1.ImageDown = null;
            this.siticoneImageButton1.ImageHover = null;
            this.siticoneImageButton1.ImageNormal = ((System.Drawing.Image)(resources.GetObject("siticoneImageButton1.ImageNormal")));
            this.siticoneImageButton1.ImageSizing = SiticoneNetFrameworkUI.ImageSizingMode.Zoom;
            this.siticoneImageButton1.IsReadOnly = true;
            this.siticoneImageButton1.Location = new System.Drawing.Point(148, 28);
            this.siticoneImageButton1.MakeRadial = false;
            this.siticoneImageButton1.Name = "siticoneImageButton1";
            this.siticoneImageButton1.PlaceholderImage = null;
            this.siticoneImageButton1.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.siticoneImageButton1.RippleEnabled = false;
            this.siticoneImageButton1.Size = new System.Drawing.Size(171, 112);
            this.siticoneImageButton1.SpringEffectEnabled = false;
            this.siticoneImageButton1.TabIndex = 6;
            this.siticoneImageButton1.Text = "siticoneImageButton1";
            this.siticoneImageButton1.TrackSystemTheme = false;
            this.siticoneImageButton1.Click += new System.EventHandler(this.siticoneImageButton1_Click);
            // 
            // siticoneTextBox11
            // 
            this.siticoneTextBox11.AccessibleDescription = "A customizable text input field.";
            this.siticoneTextBox11.AccessibleName = "Text Box";
            this.siticoneTextBox11.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.siticoneTextBox11.BackColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox11.BlinkCount = 3;
            this.siticoneTextBox11.BlinkShadow = false;
            this.siticoneTextBox11.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox11.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox11.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox11.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox11.CanShake = true;
            this.siticoneTextBox11.ContinuousBlink = false;
            this.siticoneTextBox11.Cursor = System.Windows.Forms.Cursors.Default;
            this.siticoneTextBox11.CursorBlinkRate = 500;
            this.siticoneTextBox11.CursorColor = System.Drawing.Color.Black;
            this.siticoneTextBox11.CursorHeight = 26;
            this.siticoneTextBox11.CursorOffset = 0;
            this.siticoneTextBox11.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.siticoneTextBox11.CursorWidth = 1;
            this.siticoneTextBox11.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox11.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox11.DisabledTextColor = System.Drawing.Color.Gray;
            this.siticoneTextBox11.EnableDropShadow = false;
            this.siticoneTextBox11.FillColor1 = System.Drawing.Color.White;
            this.siticoneTextBox11.FillColor2 = System.Drawing.Color.White;
            this.siticoneTextBox11.Font = new System.Drawing.Font("Segoe UI", 22.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneTextBox11.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(207)))), ((int)(((byte)(61)))));
            this.siticoneTextBox11.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.siticoneTextBox11.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.siticoneTextBox11.IsEnabled = true;
            this.siticoneTextBox11.IsReadOnly = true;
            this.siticoneTextBox11.Location = new System.Drawing.Point(133, 143);
            this.siticoneTextBox11.Name = "siticoneTextBox11";
            this.siticoneTextBox11.PlaceholderColor = System.Drawing.Color.Gray;
            this.siticoneTextBox11.PlaceholderText = "Enter text here...";
            this.siticoneTextBox11.ReadOnlyBorderColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox11.ReadOnlyBorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox11.ReadOnlyFillColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox11.ReadOnlyFillColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox11.ReadOnlyPlaceholderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox11.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox11.ShadowAnimationDuration = 1;
            this.siticoneTextBox11.ShadowBlur = 10;
            this.siticoneTextBox11.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneTextBox11.ShowBorder = false;
            this.siticoneTextBox11.Size = new System.Drawing.Size(195, 50);
            this.siticoneTextBox11.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox11.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox11.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.siticoneTextBox11.SolidFillColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox11.TabIndex = 5;
            this.siticoneTextBox11.Text = "University";
            this.siticoneTextBox11.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.siticoneTextBox11.ValidationErrorMessage = "Invalid input.";
            this.siticoneTextBox11.ValidationFunction = null;
            this.siticoneTextBox11.Click += new System.EventHandler(this.siticoneTextBox11_Click);
            // 
            // siticoneTextBox8
            // 
            this.siticoneTextBox8.AccessibleDescription = "A customizable text input field.";
            this.siticoneTextBox8.AccessibleName = "Text Box";
            this.siticoneTextBox8.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.siticoneTextBox8.BackColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox8.BlinkCount = 3;
            this.siticoneTextBox8.BlinkShadow = false;
            this.siticoneTextBox8.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox8.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox8.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox8.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox8.CanShake = true;
            this.siticoneTextBox8.ContinuousBlink = false;
            this.siticoneTextBox8.Cursor = System.Windows.Forms.Cursors.Default;
            this.siticoneTextBox8.CursorBlinkRate = 500;
            this.siticoneTextBox8.CursorColor = System.Drawing.Color.Black;
            this.siticoneTextBox8.CursorHeight = 26;
            this.siticoneTextBox8.CursorOffset = 0;
            this.siticoneTextBox8.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.siticoneTextBox8.CursorWidth = 1;
            this.siticoneTextBox8.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox8.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox8.DisabledTextColor = System.Drawing.Color.Gray;
            this.siticoneTextBox8.EnableDropShadow = false;
            this.siticoneTextBox8.FillColor1 = System.Drawing.Color.White;
            this.siticoneTextBox8.FillColor2 = System.Drawing.Color.White;
            this.siticoneTextBox8.Font = new System.Drawing.Font("Segoe UI", 22.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneTextBox8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(207)))), ((int)(((byte)(61)))));
            this.siticoneTextBox8.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.siticoneTextBox8.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.siticoneTextBox8.IsEnabled = true;
            this.siticoneTextBox8.IsReadOnly = true;
            this.siticoneTextBox8.Location = new System.Drawing.Point(47, 186);
            this.siticoneTextBox8.Name = "siticoneTextBox8";
            this.siticoneTextBox8.PlaceholderColor = System.Drawing.Color.Black;
            this.siticoneTextBox8.PlaceholderText = "Enter text here...";
            this.siticoneTextBox8.ReadOnlyBorderColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox8.ReadOnlyBorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox8.ReadOnlyFillColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox8.ReadOnlyFillColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox8.ReadOnlyPlaceholderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox8.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox8.ShadowAnimationDuration = 1;
            this.siticoneTextBox8.ShadowBlur = 10;
            this.siticoneTextBox8.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneTextBox8.ShowBorder = false;
            this.siticoneTextBox8.Size = new System.Drawing.Size(371, 60);
            this.siticoneTextBox8.SolidBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.siticoneTextBox8.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.siticoneTextBox8.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.siticoneTextBox8.SolidFillColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox8.TabIndex = 4;
            this.siticoneTextBox8.Text = "Club Management";
            this.siticoneTextBox8.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.siticoneTextBox8.ValidationErrorMessage = "Invalid input.";
            this.siticoneTextBox8.ValidationFunction = null;
            this.siticoneTextBox8.Click += new System.EventHandler(this.siticoneTextBox8_Click_1);
            // 
            // siticoneTextBox10
            // 
            this.siticoneTextBox10.AccessibleDescription = "A customizable text input field.";
            this.siticoneTextBox10.AccessibleName = "Text Box";
            this.siticoneTextBox10.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.siticoneTextBox10.BackColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox10.BlinkCount = 3;
            this.siticoneTextBox10.BlinkShadow = false;
            this.siticoneTextBox10.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox10.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox10.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox10.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox10.CanShake = true;
            this.siticoneTextBox10.ContinuousBlink = false;
            this.siticoneTextBox10.Cursor = System.Windows.Forms.Cursors.Default;
            this.siticoneTextBox10.CursorBlinkRate = 500;
            this.siticoneTextBox10.CursorColor = System.Drawing.Color.Black;
            this.siticoneTextBox10.CursorHeight = 26;
            this.siticoneTextBox10.CursorOffset = 0;
            this.siticoneTextBox10.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.siticoneTextBox10.CursorWidth = 1;
            this.siticoneTextBox10.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox10.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox10.DisabledTextColor = System.Drawing.Color.Gray;
            this.siticoneTextBox10.EnableDropShadow = false;
            this.siticoneTextBox10.FillColor1 = System.Drawing.Color.White;
            this.siticoneTextBox10.FillColor2 = System.Drawing.Color.White;
            this.siticoneTextBox10.Font = new System.Drawing.Font("Segoe UI", 22.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneTextBox10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(207)))), ((int)(((byte)(61)))));
            this.siticoneTextBox10.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.siticoneTextBox10.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.siticoneTextBox10.IsEnabled = true;
            this.siticoneTextBox10.IsReadOnly = true;
            this.siticoneTextBox10.Location = new System.Drawing.Point(166, 237);
            this.siticoneTextBox10.Name = "siticoneTextBox10";
            this.siticoneTextBox10.PlaceholderColor = System.Drawing.Color.Gray;
            this.siticoneTextBox10.PlaceholderText = "Enter text here...";
            this.siticoneTextBox10.ReadOnlyBorderColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox10.ReadOnlyBorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox10.ReadOnlyFillColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox10.ReadOnlyFillColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox10.ReadOnlyPlaceholderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox10.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox10.ShadowAnimationDuration = 1;
            this.siticoneTextBox10.ShadowBlur = 10;
            this.siticoneTextBox10.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneTextBox10.ShowBorder = false;
            this.siticoneTextBox10.Size = new System.Drawing.Size(138, 50);
            this.siticoneTextBox10.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox10.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox10.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.siticoneTextBox10.SolidFillColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox10.TabIndex = 3;
            this.siticoneTextBox10.Text = "System";
            this.siticoneTextBox10.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.siticoneTextBox10.ValidationErrorMessage = "Invalid input.";
            this.siticoneTextBox10.ValidationFunction = null;
            this.siticoneTextBox10.Click += new System.EventHandler(this.siticoneTextBox10_Click);
            // 
            // siticoneTextBox9
            // 
            this.siticoneTextBox9.AccessibleDescription = "A customizable text input field.";
            this.siticoneTextBox9.AccessibleName = "Text Box";
            this.siticoneTextBox9.AccessibleRole = System.Windows.Forms.AccessibleRole.Text;
            this.siticoneTextBox9.BackColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox9.BlinkCount = 3;
            this.siticoneTextBox9.BlinkShadow = false;
            this.siticoneTextBox9.BorderColor1 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox9.BorderColor2 = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox9.BorderFocusColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox9.BorderFocusColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox9.CanShake = true;
            this.siticoneTextBox9.ContinuousBlink = false;
            this.siticoneTextBox9.Cursor = System.Windows.Forms.Cursors.Default;
            this.siticoneTextBox9.CursorBlinkRate = 500;
            this.siticoneTextBox9.CursorColor = System.Drawing.Color.Black;
            this.siticoneTextBox9.CursorHeight = 26;
            this.siticoneTextBox9.CursorOffset = 0;
            this.siticoneTextBox9.CursorStyle = SiticoneNetFrameworkUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            this.siticoneTextBox9.CursorWidth = 1;
            this.siticoneTextBox9.DisabledBackColor = System.Drawing.Color.WhiteSmoke;
            this.siticoneTextBox9.DisabledBorderColor = System.Drawing.Color.LightGray;
            this.siticoneTextBox9.DisabledTextColor = System.Drawing.Color.Gray;
            this.siticoneTextBox9.EnableDropShadow = false;
            this.siticoneTextBox9.FillColor1 = System.Drawing.Color.White;
            this.siticoneTextBox9.FillColor2 = System.Drawing.Color.White;
            this.siticoneTextBox9.Font = new System.Drawing.Font("Comic Sans MS", 19.8F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneTextBox9.ForeColor = System.Drawing.Color.White;
            this.siticoneTextBox9.HoverBorderColor1 = System.Drawing.Color.Gray;
            this.siticoneTextBox9.HoverBorderColor2 = System.Drawing.Color.Gray;
            this.siticoneTextBox9.IsEnabled = true;
            this.siticoneTextBox9.IsReadOnly = true;
            this.siticoneTextBox9.Location = new System.Drawing.Point(100, 325);
            this.siticoneTextBox9.Name = "siticoneTextBox9";
            this.siticoneTextBox9.PlaceholderColor = System.Drawing.Color.Gray;
            this.siticoneTextBox9.PlaceholderText = "Enter text here...";
            this.siticoneTextBox9.ReadOnlyBorderColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox9.ReadOnlyBorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox9.ReadOnlyFillColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox9.ReadOnlyFillColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox9.ReadOnlyPlaceholderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(17)))), ((int)(((byte)(17)))));
            this.siticoneTextBox9.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox9.ShadowAnimationDuration = 1;
            this.siticoneTextBox9.ShadowBlur = 10;
            this.siticoneTextBox9.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneTextBox9.ShowBorder = false;
            this.siticoneTextBox9.Size = new System.Drawing.Size(264, 45);
            this.siticoneTextBox9.SolidBorderColor = System.Drawing.Color.LightSlateGray;
            this.siticoneTextBox9.SolidBorderFocusColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(255)))));
            this.siticoneTextBox9.SolidBorderHoverColor = System.Drawing.Color.Gray;
            this.siticoneTextBox9.SolidFillColor = System.Drawing.Color.Transparent;
            this.siticoneTextBox9.TabIndex = 2;
            this.siticoneTextBox9.Text = "Welcome Back!";
            this.siticoneTextBox9.TextPadding = new System.Windows.Forms.Padding(16, 0, 6, 0);
            this.siticoneTextBox9.ValidationErrorMessage = "Invalid input.";
            this.siticoneTextBox9.ValidationFunction = null;
            this.siticoneTextBox9.Click += new System.EventHandler(this.siticoneTextBox9_Click);
            // 
            // Login
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.ClientSize = new System.Drawing.Size(1124, 598);
            this.Controls.Add(this.siticonePanel1);
            this.Controls.Add(this.siticonePanel2);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(4);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "Login";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Sign In Page";
            this.Load += new System.EventHandler(this.Login_Load);
            this.siticonePanel2.ResumeLayout(false);
            this.siticonePanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private SiticoneNetFrameworkUI.MySiticoneLicenseSettings mySiticoneLicenseSettings1;
        private SiticoneNetFrameworkUI.SiticonePanel siticonePanel2;
        private SiticoneNetFrameworkUI.SiticoneTextBox siticoneTextBox1;
        private SiticoneNetFrameworkUI.SiticonePanel siticonePanel1;
        private SiticoneNetFrameworkUI.SiticoneTextBox siticoneTextBox2;
        private SiticoneNetFrameworkUI.SiticoneTextBox siticoneTextBox3;
        private SiticoneNetFrameworkUI.SiticoneTextBox siticoneTextBox4;
        private SiticoneNetFrameworkUI.SiticoneTextBox siticoneTextBox6;
        private SiticoneNetFrameworkUI.SiticoneTextBox siticoneTextBox5;
        private SiticoneNetFrameworkUI.SiticoneTextButton siticoneTextButton1;
        private SiticoneNetFrameworkUI.SiticoneButton siticoneButton1;
        private SiticoneNetFrameworkUI.SiticoneTextButton siticoneTextButton2;
        private SiticoneNetFrameworkUI.SiticoneTextBox siticoneTextBox7;
        private SiticoneNetFrameworkUI.SiticoneCheckBox siticoneCheckBox1;
        private SiticoneNetFrameworkUI.SiticoneTextBox siticoneTextBox10;
        private SiticoneNetFrameworkUI.SiticoneTextBox siticoneTextBox9;
        private SiticoneNetFrameworkUI.SiticoneTextBox siticoneTextBox8;
        private SiticoneNetFrameworkUI.SiticoneTextBox siticoneTextBox11;
        private SiticoneNetFrameworkUI.SiticoneImageButton siticoneImageButton1;
    }
}

